spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.88.0.11:8848
  redis:
    database: 0
    host: 172.88.0.13
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0