spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.88.0.11:8848
  redis:
    database: 0
    host: 172.88.0.13
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

dubbo:
  protocols:
    dubbo:
      name: dubbo # 服务协议
      port: -1 # 服务端口
  registry:
    address: spring-cloud://172.88.0.11 # 注册中心
#    address: spring-cloud://192.168.124.17 # 注册中心
    port: 8848
  cloud:
    subscribed-services: service-user  # 订阅的提供者名称
