spring:
  profiles:
#    active: test
    active: dev
#    active: produce
  application:
    name: api-user
  servlet:
    multipart:
      #文件上传限制
      max-file-size: -1
      max-request-size: -1

server:
  port: 10200

# 用于nacos的健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
